//===- Interfaces.td - CFDlang interface declarations ------*- tablegen -*-===//
//
// TODO: Add license.
//
//===----------------------------------------------------------------------===//
//
// This is the definitions file for the CFDlang interfaces.
//
//===----------------------------------------------------------------------===//

#ifndef CFDLANG_INTERFACES
#define CFDLANG_INTERFACES

include "mlir/IR/OpBase.td"

#endif
