//===- Ops.td - CFDlang op declarations --------------------*- tablegen -*-===//
//
// TODO: Add license.
//
//===----------------------------------------------------------------------===//
//
// This is the definitions file for the CFDlang dialect ops.
//
//===----------------------------------------------------------------------===//

#ifndef CFDLANG_OPS
#define CFDLANG_OPS

include "mlir/Dialect/CFDlang/IR/Interfaces.td"
include "mlir/Dialect/CFDlang/IR/Types.td"

#endif
