//===- Interfaces.td - TeIL interface declarations ---------*- tablegen -*-===//
//
// TODO: Add license.
//
//===----------------------------------------------------------------------===//
//
// This is the definitions file for the TeIL dialect interfaces.
//
//===----------------------------------------------------------------------===//

#ifndef TEIL_INTERFACES
#define TEIL_INTERFACES

include "mlir/IR/OpBase.td"

#endif
