//===- Ops.td - TeIL op declarations -----------------------*- tablegen -*-===//
//
// TODO: Add license.
//
//===----------------------------------------------------------------------===//
//
// This is the definitions file for the TeIL dialect ops.
//
//===----------------------------------------------------------------------===//

#ifndef TEIL_OPS
#define TEIL_OPS

include "mlir/Dialect/TeIL/IR/Interfaces.td"
include "mlir/Dialect/TeIL/IR/Types.td"

#endif
