//===- Interfaces.td ---------------------------------------*- tablegen -*-===//
//
// This is the convenience include for all EKL dialect interfaces.
//
//===----------------------------------------------------------------------===//

#ifndef EKL_INTERFACES
#define EKL_INTERFACES

include "messner/Dialect/EKL/Interfaces/ContiguousType.td"
include "messner/Dialect/EKL/Interfaces/TypeCheckOpInterface.td"

#endif
